/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include "my_led.h"

void GPIO_Init(void)
{
    /* Enable GPIOA and GPIOD clock */
    RCC->AHB1ENR |= (1U << 0);   // GPIOA
    RCC->AHB1ENR |= (1U << 3);   // GPIOD

    /* PA0 as INPUT */
    GPIOA->MODER &= ~(3U << (0 * 2));

    /* Pull-down for PA0 */
    GPIOA->PUPDR &= ~(3U << (0 * 2));
    GPIOA->PUPDR |=  (2U << (0 * 2));

    /* PD14 as OUTPUT (Red LED) */
    GPIOD->MODER &= ~(3U << (14 * 2));
    GPIOD->MODER |=  (1U << (14 * 2));
}

uint8_t Read_Switch(void)
{
    return (GPIOA->IDR & (1U << 0)) ? 1 : 0;
}

void LED_Toggle(void)
{
    GPIOD->ODR ^= (1U << 14);
}








